"""Trim the Statcast CSV to the columns the tutorial uses.

Writes data/skubal.csv (for d3.csv over a local server) and data/skubal.js
(the same rows embedded as JavaScript, so the tutorial also works from file://).

Source: Baseball Savant (https://baseballsavant.mlb.com), Statcast search,
downloaded 2026-09-08. Copyright MLB Advanced Media, L.P. This excerpt is
included for teaching and non-commercial educational use; no ownership claimed.
"""
import csv, json, pathlib

import sys

OUT = pathlib.Path(__file__).parent
# The raw export: pass its path as the only argument, or save it as data/statcast_export.csv.
SRC = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else OUT / "statcast_export.csv"

KEEP = ["game_date", "inning", "at_bat_number", "pitch_number", "pitch_type", "pitch_name",
        "release_speed", "release_spin_rate", "release_pos_x", "release_pos_z",
        "pfx_x", "pfx_z", "plate_x", "plate_z", "sz_top", "sz_bot", "stand",
        "balls", "strikes", "description", "events", "launch_speed"]
NUMERIC = {"inning", "at_bat_number", "pitch_number", "release_speed", "release_spin_rate",
           "release_pos_x", "release_pos_z", "pfx_x", "pfx_z", "plate_x", "plate_z",
           "sz_top", "sz_bot", "balls", "strikes", "launch_speed"}
ROUND = {"release_pos_x": 2, "release_pos_z": 2, "pfx_x": 3, "pfx_z": 3, "plate_x": 3,
         "plate_z": 3, "sz_top": 2, "sz_bot": 2, "release_speed": 1, "launch_speed": 1}

rows = []
with SRC.open(encoding="utf-8-sig") as f:
    for r in csv.DictReader(f):
        row = {}
        for k in KEEP:
            v = r[k]
            if k in NUMERIC:
                v = round(float(v), ROUND.get(k, 0)) if v != "" else None
                if v is not None and k not in ROUND: v = int(v)
            row[k] = v
        rows.append(row)

# Chronological order: game, at-bat, pitch.
rows.sort(key=lambda d: (d["game_date"], d["at_bat_number"], d["pitch_number"]))
assert len(rows) == 495, len(rows)

with (OUT / "skubal.csv").open("w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=KEEP)
    w.writeheader()
    for d in rows:
        w.writerow({k: ("" if v is None else v) for k, v in d.items()})

csv_text = (OUT / "skubal.csv").read_text()
with (OUT / "skubal.js").open("w") as f:
    f.write("// Generated by data/make_data.py. Do not edit by hand.\n")
    f.write("// Source: Baseball Savant (https://baseballsavant.mlb.com), Statcast search, downloaded 2026-09-08.\n")
    f.write("// Copyright MLB Advanced Media, L.P. This excerpt is included for teaching and non-commercial\n")
    f.write("// educational use; no ownership claimed. Download the data from Baseball Savant for other uses.\n")
    f.write("// Tarik Skubal, %d pitches, %s to %s.\n" % (len(rows), rows[0]["game_date"], rows[-1]["game_date"]))
    f.write("window.pitches = [\n" + ",\n".join(json.dumps(d, separators=(",", ":")) for d in rows) + "\n];\n")
    f.write("window.pitchesCSV = " + json.dumps(csv_text) + ";\n")
print(len(rows), "rows;", sum(1 for d in rows if d["launch_speed"] is not None), "with launch_speed")
